### ISSUE TITLE
Goland error

### ISSUE THREAD

**Issue by kerrywei** [cadence-tools/cadence-for-intellij-platform#16]
Hi there! 
First of all, thank you for building this awesome tool! 
I'm trying to use it in GoLand, the syntax highlighting feature works, however, I can not get semantic analysis work. 
I followed the installation instruction in https://github.com/cadence-tools/cadence-for-intellij-platform#installation , though got error when opening the crypto-dappy project: 
`Can't start server due to Cannot run program "flow" (in directory "/Users/kerrywei/repos/crypto-dappy"): error=2, No such file or directory`
![Screen Shot 2021-11-08 at 11 32 21 AM](https://user-images.githubusercontent.com/91617737/140782756-a60a6949-fec3-4565-8246-5064d3f92089.png)

I did verified that I can run the flow command in any location

**Comment by qq976739120** [comment]
I also have this problem

**Comment by qq976739120** [comment]
I also have this problem

**Comment by NikitasKotsolakos** [comment]
Hello @kerrywei  and @qq976739120 
I just tested again with GoLand specifically (version 2021.2.4, although any version where you can get the plugin should work without issues), and for me it seems to work
Can you please:
1. Confirm that in `Settings` -> `Tools` -> `Cadence Settings` you have set correctly the path pointing to your `flow.json` init file
2. If it wasn't, after the above, restart GoLand
3. If you are still having problems, let me know of your exact version / OS , so I can try to replicate?

Thanks a lot

**Comment by kerrywei** [comment]
@NikitasKotsolakos 
I git cloned https://github.com/bebner/crypto-dappy as an example, and this is my config: 
![Screen Shot 2021-11-09 at 11 20 15 AM](https://user-images.githubusercontent.com/91617737/140963045-388a72f1-882d-4902-8ff4-5b6f7d609db2.png)

I did both 1 and 2. 
My Mac OS version: 11.6.1 (20G224)
Goland version: 2021.2.4

**Comment by NikitasKotsolakos** [comment]
Hmmm, as I had mentioned in the flip-fest issue, Mac is the only one I didn't have and couldn't test.
I will create a VM with MAC though, and investigate today

**Comment by NikitasKotsolakos** [comment]
Hello @kerrywei ,
I was able to reproduce the issue, it appears to be a MacOs specific issue (which also doesn't appear when developing the plugin and running it through the development environment, of course :P )

I have confirmed a workaround, if I provide the full path to the flow executable instead of calling the command flow.
Thus, I plan to create a small update that allows you to set it as a setting (the same way we do for flow.json).
This would enable you to run the language server support, and in the following days I can investigate the issue more (since I am not familiar with MacOs it might take me more than it would for a linux issue).
Is this ok?

**Comment by NikitasKotsolakos** [comment]
Hello @kerrywei ,

I have published a new version, which allows you to set the path to the flow executable on the settings, to work around the issue.
It will take a couple of business days for it to be published, but you can download the release zip and install it from disk:

https://github.com/cadence-tools/cadence-for-intellij-platform/releases/download/v0.4.3/cadence-for-intellij-platform-0.4.3-signed.zip

![install-from-disk](https://user-images.githubusercontent.com/15243974/141012860-ee2b43fe-ebde-4864-8e21-b2297bf75a9e.png)

**Comment by kerrywei** [comment]
@NikitasKotsolakos thank you for unblocking me! I verified this workaround works on Mac.
Great work on this plugin and looking forward to future improvements!
