### ISSUE TITLE
Idea 2021.3 support

### ISSUE THREAD

**Issue by phil-bl** [cadence-tools/cadence-for-intellij-platform#17]
First of all, thank you for this great plugin!
Intellij Idea 2021.3 is out now - do you have any plans to release a compatible version?

**Comment by NikitasKotsolakos** [comment]
Hello @phil-bl ,

I would have expected that the plugin would work out of the box (since I only specified "minimum" version), but I will take a look and do any changes required if that's not the case. So, I will be checking this the next days

**Comment by NikitasKotsolakos** [comment]
Hello @phil-bl ,

I have fixed the compatibility issue (it was a default setting I was not aware of).
I have submitted the update to Jetbrains, usually it is approved within 1 business day (they say up to 2).

If you need it before that, you can download the signed zip from the [github release](https://github.com/cadence-tools/cadence-for-intellij-platform/releases/download/v0.4.4/cadence-for-intellij-platform-0.4.4-signed.zip) and install it from disk, but if it is not too urgent I would suggest wait for the day to get it normally through the marketplace.

I will leave this issue open, until the plugin is available from the marketplace and I have tested installation from there works as expected.

**Comment by phil-bl** [comment]
Hello Nikitas,

Updated from JetBrains marketplace, it works, thanks! :)

**Comment by NikitasKotsolakos** [comment]
Perfect, tested myself also.
With the changes done, this shouldn't happen again in new versions (unless there are real compatibility issues).
