### ISSUE TITLE
Add support for in-line cadence

### ISSUE THREAD

**Issue by briandilley** [cadence-tools/cadence-for-intellij-platform#18]
I am one of the maintainers of the flow jvm sdk and use idea quite often. I'm super excited by this plugin and have just started using it and have high hopes for it. Thanks for your work!

I am often using IDEA for JVM related things and using the flow-jvm-sdk often. The flow-jvm-sdk has a number of facilities for executing transactions through a fairly robust DSL. With this DSL you can actually have your cadence scripts in-line in the code rather than in a separate .cdc file and this is very convenient. I was hoping that we could add support for syntax highlighting the cadence code in-line, much like how SQL works in IDEA.

Here's an example snippet using the flow-jvm-sdk that I'd like to see support for cadence in:

```
        val result = flow.simpleFlowScript {
            script {
                """
                    import FungibleToken from 0xFUNGIBLETOKEN
                    
                    pub fun main(address: Address): UFix64 {
                    
                        let account = getAccount(address)
                        
                        let vault = account
                            .getCapability(/public/somePathHere)
                            .borrow<&{FungibleToken.Balance}>()
                            ?? panic("Could not borrow Balance reference to the Vault")
                            
                        return vault.balance
                    }
                """
            }
            arg { address(address) }
        }
```

Thanks!

**Comment by phil-bl** [comment]
@briandilley I usually hit "Show context actions" (Option+Enter on Mac) -> Inject language -> Cadence and it turns on syntax highlighting in strings

**Comment by NikitasKotsolakos** [comment]
Hi @briandilley , can you tell me if phil's suggestion works as a workaround for you?
If not I can take a look to see what would be needed for it, but don't have any idea currently what is needed / how long it would take

**Comment by NikitasKotsolakos** [comment]
Since no response, I am closing this for now assuming the workaround works
